# MODIF FROM SOURCE: https://github.com/bitnami/containers/blob/main/bitnami/spark/docker-compose.yml
# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile.Spark
    image: ${SPARK_IMAGE_NAME:-spark:latest}
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8090:8080'
    networks:
      default:
        ipv4_address: 172.21.1.2

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.Spark
    image: ${SPARK_IMAGE_NAME:-spark:latest}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ${ETL_SCRIPT_DIR:-.}/etl:/opt/bitnami/spark/etl

networks:
  default:
    ipam:
      config:
        - subnet: 172.21.0.0/16